//! Generates the wrapper script and keeps `primer-config/` in sync, and runs a
//! primer on demand (catch-up / "Prime now"). The wrapper is what cron/Task
//! Scheduler fires; `run_primer` runs `claude` directly for the in-app path so
//! it can return a `ScheduleRun` to the UI. Both append the same record shape
//! to `runs.jsonl`.

use std::path::Path;

use chrono::Utc;

use crate::models::{AppError, AppResult, ScheduleRun};
use crate::schedule::runs::append_run;
use crate::state::AppState;

/// Model the primer invokes. The `haiku` alias resolves to the cheapest,
/// fastest model — a real message on the subscription token that resets the
/// 5-hour window for a sliver of quota.
pub const PRIMER_MODEL: &str = "haiku";

/// `settings.json` for the isolated primer config: an empty `env` block, which
/// forces `claude` to fall back to `.credentials.json` OAuth (the subscription)
/// regardless of which provider is currently loaded globally.
pub fn render_primer_settings() -> serde_json::Value {
    serde_json::json!({ "env": {} })
}

/// POSIX `sh` wrapper. `$1` is the schedule id. Uses `timeout` when available.
#[allow(dead_code)] // unused on windows builds; selected by `render_wrapper`.
pub fn render_wrapper_unix(config_dir: &Path, runs_path: &Path, model: &str) -> String {
    let config = config_dir.display();
    let runs = runs_path.display();
    format!(
        r#"#!/bin/sh
# Generated by claude-config. Do not edit — regenerated from schedules.json.
SCHEDULE_ID="$1"
STARTED=$(date -u +%Y-%m-%dT%H:%M:%SZ)
if command -v timeout >/dev/null 2>&1; then
  CLAUDE_CONFIG_DIR="{config}" timeout 120 claude -p "hi" --model {model} >/dev/null 2>&1
else
  CLAUDE_CONFIG_DIR="{config}" claude -p "hi" --model {model} >/dev/null 2>&1
fi
CODE=$?
if [ "$CODE" -eq 0 ]; then OK=true; else OK=false; fi
printf '{{"scheduleId":"%s","startedAt":"%s","exitCode":%s,"ok":%s}}\n' "$SCHEDULE_ID" "$STARTED" "$CODE" "$OK" >> "{runs}"
"#
    )
}

/// Windows `.cmd` wrapper. `%1` is the schedule id. Best-effort.
#[allow(dead_code)] // unused on unix builds; selected by `render_wrapper`.
pub fn render_wrapper_windows(config_dir: &Path, runs_path: &Path, model: &str) -> String {
    let config = config_dir.display();
    let runs = runs_path.display();
    format!(
        r#"@echo off
setlocal
set "SCHEDULE_ID=%~1"
set "CLAUDE_CONFIG_DIR={config}"
for /f "usebackq delims=" %%t in (`powershell -NoProfile -Command "(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')"`) do set "STARTED=%%t"
claude -p "hi" --model {model} >nul 2>&1
set "CODE=%ERRORLEVEL%"
if "%CODE%"=="0" (set "OK=true") else (set "OK=false")
>> "{runs}" echo {{"scheduleId":"%SCHEDULE_ID%","startedAt":"%STARTED%","exitCode":%CODE%,"ok":%OK%}}
"#
    )
}

/// Render the wrapper for the current platform.
pub fn render_wrapper(config_dir: &Path, runs_path: &Path, model: &str) -> String {
    #[cfg(windows)]
    {
        render_wrapper_windows(config_dir, runs_path, model)
    }
    #[cfg(not(windows))]
    {
        render_wrapper_unix(config_dir, runs_path, model)
    }
}

/// Write the wrapper script, making it executable on unix.
pub fn write_wrapper(path: &Path, contents: &str) -> AppResult<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

/// Keep `primer-config/` in sync: an empty-env `settings.json` plus a fresh
/// reference to `.credentials.json` (symlink on unix, copy on Windows).
pub fn sync_primer_config(config_dir: &Path) -> AppResult<()> {
    std::fs::create_dir_all(config_dir)?;
    let settings_path = config_dir.join("settings.json");
    std::fs::write(&settings_path, serde_json::to_vec_pretty(&render_primer_settings())?)?;
    sync_primer_credentials(config_dir)?;
    Ok(())
}

#[cfg(unix)]
fn sync_primer_credentials(config_dir: &Path) -> AppResult<()> {
    use std::os::unix::fs::symlink;
    let target = crate::storage::credentials_path();
    let link = config_dir.join(".credentials.json");
    // Always recreate the symlink so a rotated token is picked up.
    if std::fs::symlink_metadata(&link).is_ok() {
        let _ = std::fs::remove_file(&link);
    }
    if target.exists() {
        symlink(&target, &link).map_err(AppError::Io)?;
    }
    Ok(())
}

#[cfg(windows)]
fn sync_primer_credentials(config_dir: &Path) -> AppResult<()> {
    let target = crate::storage::credentials_path();
    let dest = config_dir.join(".credentials.json");
    if target.exists() {
        // Refresh-copy. Windows ACL hardening is out of scope; the file mirrors
        // the same plaintext credentials as the default location.
        std::fs::copy(&target, &dest)?;
    }
    Ok(())
}

/// Fire a primer immediately (used by "Prime now" and launch catch-up). Runs
/// `claude` under the isolated config dir, records the outcome to `runs.jsonl`,
/// and returns the run record. Never returns `Err` — a failed primer is data,
/// not an error (self-heals once Claude Code refreshes the token).
pub fn run_primer(state: &AppState, schedule_id: &str) -> ScheduleRun {
    let started_at = Utc::now().to_rfc3339();
    let config_dir = state.primer_config_dir();
    if let Err(e) = sync_primer_config(&config_dir) {
        log::warn!("primer-config sync failed before run: {e}");
    }

    let status = std::process::Command::new("claude")
        .env("CLAUDE_CONFIG_DIR", &config_dir)
        .args(["-p", "hi", "--model", PRIMER_MODEL])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status();

    let run = match status {
        Ok(s) => ScheduleRun {
            schedule_id: schedule_id.to_string(),
            started_at,
            exit_code: s.code(),
            ok: s.success(),
            error: if s.success() {
                None
            } else {
                Some(format!("claude exited with {:?}", s.code()))
            },
        },
        Err(e) => ScheduleRun {
            schedule_id: schedule_id.to_string(),
            started_at,
            exit_code: None,
            ok: false,
            error: Some(format!("failed to spawn claude: {e}")),
        },
    };

    if let Err(e) = append_run(&state.runs_path(), &run) {
        log::warn!("failed to append primer run record: {e}");
    }
    run
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn primer_settings_is_empty_env() {
        let v = render_primer_settings();
        assert!(v["env"].is_object());
        assert_eq!(v["env"].as_object().unwrap().len(), 0);
    }

    #[test]
    fn unix_wrapper_has_isolated_config_and_command() {
        let w = render_wrapper_unix(
            &PathBuf::from("/app/primer-config"),
            &PathBuf::from("/app/runs.jsonl"),
            "haiku",
        );
        assert!(w.contains("CLAUDE_CONFIG_DIR=\"/app/primer-config\""));
        assert!(w.contains("claude -p \"hi\" --model haiku"));
        assert!(w.contains(">> \"/app/runs.jsonl\""));
        assert!(w.contains("\"scheduleId\":\"%s\""));
        assert!(w.starts_with("#!/bin/sh"));
    }

    #[test]
    fn windows_wrapper_has_isolated_config_and_command() {
        let w = render_wrapper_windows(
            &PathBuf::from(r"C:\app\primer-config"),
            &PathBuf::from(r"C:\app\runs.jsonl"),
            "haiku",
        );
        assert!(w.contains(r#"set "CLAUDE_CONFIG_DIR=C:\app\primer-config""#));
        assert!(w.contains("claude -p \"hi\" --model haiku"));
        assert!(w.contains("scheduleId"));
    }

    #[test]
    #[ignore] // touches the real filesystem symlink; run explicitly.
    fn sync_primer_config_writes_settings() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = dir.path().join("primer-config");
        sync_primer_config(&cfg).unwrap();
        let settings = std::fs::read_to_string(cfg.join("settings.json")).unwrap();
        assert!(settings.contains("\"env\""));
    }
}
